package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

func runInstall() error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	binDir := filepath.Join(home, ".lancer", "bin")
	if err := os.MkdirAll(binDir, 0700); err != nil {
		return err
	}
	target := filepath.Join(binDir, "lancerd")
	if exe != target {
		data, err := os.ReadFile(exe)
		if err != nil {
			return fmt.Errorf("read binary: %w", err)
		}
		if err := os.WriteFile(target, data, 0755); err != nil {
			return fmt.Errorf("install binary: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Installed %s\n", target)
	}

	if err := installClaudeHook(home); err != nil {
		// Hook wiring is best-effort: a failure here must not abort the daemon
		// install. Surface it so the owner can wire the hook by hand.
		fmt.Fprintf(os.Stderr, "warning: could not wire Claude PreToolUse hook: %v\n", err)
		fmt.Fprintln(os.Stderr, "  wire it manually — see docs/claude-settings-hook.json")
	}

	// Shim wrappers let a plain `claude`/`codex`/… launched in any terminal be
	// intercepted by the daemon (run in tmux, registered, pushed to the phone)
	// instead of running invisibly. Best-effort: a failure must not abort install.
	if err := installShimWrappers(home, binDir, target); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not install shim wrappers: %v\n", err)
	}
	fmt.Fprintln(os.Stderr, "Claude approvals apply only to runs started by Lancer; your normal Claude sessions are unchanged.")
	// TODO(opencode): wire the OpenCode PreToolUse hook (docs/opencode-hooks.json,
	// ~/.config/opencode/hooks/lancer-hook.sh) the same way once OpenCode
	// settings-merge is in scope. Finding #10 covers the Claude path above.

	switch runtime.GOOS {
	case "darwin":
		return installLaunchd(target, home)
	case "linux":
		return installSystemd(target, home)
	default:
		fmt.Fprintf(os.Stderr, "Unsupported OS %s — install binary only.\n", runtime.GOOS)
		return nil
	}
}

// shimAgents are the vendor CLIs the daemon can intercept via PATH wrappers.
var shimAgents = []string{"claude", "codex", "opencode", "kimi"}

// installShimWrappers writes a wrapper script per installed agent into
// ~/.lancer/bin. Each wrapper hands the launch to `lancerd shim <agent>`, which
// runs it in a daemon-tracked tmux session (visible on the phone) or, if the
// daemon is unreachable, falls back to the real binary via LANCER_REAL_<agent>.
// The real binary is resolved EXCLUDING binDir so re-running install never
// points a wrapper at itself.
func installShimWrappers(home, binDir, lancerd string) error {
	var made, skipped []string
	for _, agent := range shimAgents {
		real := lookPathExcluding(agent, binDir)
		if real == "" {
			skipped = append(skipped, agent)
			continue
		}
		script := fmt.Sprintf(
			"#!/bin/sh\n"+
				"# Lancer shim wrapper — intercepts %s so daemon-tracked sessions\n"+
				"# show up in the Lancer app. Regenerated by `lancerd install`.\n"+
				"export LANCER_REAL_%s=%q\n"+
				"exec %q shim %s \"$@\"\n",
			agent, agent, real, lancerd, agent)
		wrapper := filepath.Join(binDir, agent)
		if err := os.WriteFile(wrapper, []byte(script), 0755); err != nil {
			return fmt.Errorf("write %s wrapper: %w", agent, err)
		}
		made = append(made, agent)
	}
	if len(made) > 0 {
		fmt.Fprintf(os.Stderr, "Installed shim wrappers for: %v\n", made)
	}
	if len(skipped) > 0 {
		fmt.Fprintf(os.Stderr, "Skipped (not installed): %v\n", skipped)
	}
	fmt.Fprintf(os.Stderr,
		"To intercept terminal-started agents, put the Lancer bin FIRST on PATH:\n"+
			"  echo 'export PATH=\"$HOME/.lancer/bin:$PATH\"' >> ~/.zshrc && exec zsh\n")
	return nil
}

// lookPathExcluding resolves an executable on PATH, skipping any match inside
// excludeDir (so a shim wrapper never resolves to itself).
func lookPathExcluding(name, excludeDir string) string {
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" || dir == excludeDir {
			continue
		}
		cand := filepath.Join(dir, name)
		if fi, err := os.Stat(cand); err == nil && !fi.IsDir() && fi.Mode()&0111 != 0 {
			return cand
		}
	}
	return ""
}

// installClaudeHook drops the PreToolUse hook script to ~/.claude/hooks and
// idempotently wires it into ~/.claude/settings.json so Claude Code actually
// calls it. Without the settings wiring the interactive approval path never
// fires (Finding #10).
// ensureClaudeHookWiredOnBoot wires the Claude PreToolUse hook on daemon startup
// if it isn't already. This is what lets a plain dispatch ("Hi") launch
// immediately instead of escalating: relaxLaunchEscalation only relaxes a launch
// when the per-action hook is verifiably wired, so without this a fresh/rebranded
// install silently forces approval on every send. Idempotent and best-effort — a
// wiring failure only means more prompting, never an unintended allow.
func ensureClaudeHookWiredOnBoot() {
	home := serverHome()
	if claudeHookWired(claudeSettingsPath(home)) {
		return
	}
	if err := installClaudeHook(home); err != nil {
		fmt.Fprintf(os.Stderr, "lancerd: could not auto-wire Claude hook (sends will require approval): %v\n", err)
	}
}

func installClaudeHook(home string) error {
	scriptPath := claudeHookScriptPath(home)
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(scriptPath, []byte(claudeHookScript), 0755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", scriptPath)

	changed, err := wireClaudeHookSettings(home)
	if err != nil {
		return err
	}
	if changed {
		fmt.Fprintf(os.Stderr, "Enabled Lancer-scoped Claude approvals in %s\n", claudeSettingsPath(home))
	} else {
		fmt.Fprintf(os.Stderr, "Lancer-scoped Claude approvals already enabled in %s\n", claudeSettingsPath(home))
	}
	return nil
}

func installLaunchd(binary, home string) error {
	plistPath := launchdPlistPath(home)
	if err := os.MkdirAll(filepath.Dir(plistPath), 0755); err != nil {
		return err
	}
	plist := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.lancer.lancerd</string>
  <key>ProgramArguments</key>
  <array>
    <string>%s</string>
    <string>daemon</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>%s</string>
  <key>StandardErrorPath</key><string>%s</string>
</dict>
</plist>
`, binary, filepath.Join(home, ".lancer", "lancerd.stdout.log"), filepath.Join(home, ".lancer", "lancerd.stderr.log"))
	if err := os.WriteFile(plistPath, []byte(plist), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", plistPath)
	fmt.Fprintln(os.Stderr, "Owner steps:")
	fmt.Fprintf(os.Stderr, "  launchctl unload %s 2>/dev/null || true\n", plistPath)
	fmt.Fprintf(os.Stderr, "  launchctl load %s\n", plistPath)
	return nil
}

func installSystemd(binary, home string) error {
	unitDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(unitDir, 0755); err != nil {
		return err
	}
	unitPath := filepath.Join(unitDir, "lancerd.service")
	unit := fmt.Sprintf(`[Unit]
Description=Lancer resident bridge daemon

[Service]
ExecStart=%s daemon
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
`, binary)
	if err := os.WriteFile(unitPath, []byte(unit), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", unitPath)
	fmt.Fprintln(os.Stderr, "Owner steps:")
	fmt.Fprintln(os.Stderr, "  systemctl --user daemon-reload")
	fmt.Fprintln(os.Stderr, "  systemctl --user enable --now lancerd.service")
	if _, err := exec.LookPath("systemctl"); err == nil {
		_ = exec.Command("systemctl", "--user", "daemon-reload").Run()
	}
	return nil
}
