package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

func runInstall() error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	binDir := filepath.Join(home, ".lancer", "bin")
	if err := os.MkdirAll(binDir, 0700); err != nil {
		return err
	}
	target := filepath.Join(binDir, "lancerd")
	if exe != target {
		data, err := os.ReadFile(exe)
		if err != nil {
			return fmt.Errorf("read binary: %w", err)
		}
		if err := os.WriteFile(target, data, 0755); err != nil {
			return fmt.Errorf("install binary: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Installed %s\n", target)
	}

	if err := installClaudeHook(home); err != nil {
		// Hook wiring is best-effort: a failure here must not abort the daemon
		// install. Surface it so the owner can wire the hook by hand.
		fmt.Fprintf(os.Stderr, "warning: could not wire Claude PreToolUse hook: %v\n", err)
		fmt.Fprintln(os.Stderr, "  wire it manually — see docs/claude-settings-hook.json")
	}

	// Shim wrappers let a plain `claude`/`codex`/… launched in any terminal be
	// intercepted by the daemon (run in tmux, registered, pushed to the phone)
	// instead of running invisibly. Best-effort: a failure must not abort install.
	if err := installShimWrappers(home, binDir, target); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not install shim wrappers: %v\n", err)
	}
	fmt.Fprintln(os.Stderr, "Claude approvals apply only to runs started by Lancer; your normal Claude sessions are unchanged.")

	if err := installOpencodeGate(home); err != nil {
		// Best-effort, same as the Claude hook above: a failure here must not
		// abort the daemon install.
		fmt.Fprintf(os.Stderr, "warning: could not wire OpenCode tool.execute.before gate: %v\n", err)
		fmt.Fprintln(os.Stderr, "  wire it manually — see docs/opencode-lancer-gate-plugin.js")
	}

	switch runtime.GOOS {
	case "darwin":
		return installLaunchd(target, home)
	case "linux":
		return installSystemd(target, home)
	default:
		fmt.Fprintf(os.Stderr, "Unsupported OS %s — install binary only.\n", runtime.GOOS)
		return nil
	}
}

// shimAgents are the vendor CLIs the daemon can intercept via PATH wrappers.
var shimAgents = []string{"claude", "codex", "opencode", "kimi"}

// installShimWrappers writes a wrapper script per installed agent into
// ~/.lancer/bin. Each wrapper hands the launch to `lancerd shim <agent>`, which
// runs it in a daemon-tracked tmux session (visible on the phone) or, if the
// daemon is unreachable, falls back to the real binary via LANCER_REAL_<agent>.
// The real binary is resolved EXCLUDING binDir so re-running install never
// points a wrapper at itself.
func installShimWrappers(home, binDir, lancerd string) error {
	var made, skipped []string
	for _, agent := range shimAgents {
		real := lookPathExcluding(agent, binDir)
		if real == "" {
			skipped = append(skipped, agent)
			continue
		}
		script := fmt.Sprintf(
			"#!/bin/sh\n"+
				"# Lancer shim wrapper — intercepts %s so daemon-tracked sessions\n"+
				"# show up in the Lancer app. Regenerated by `lancerd install`.\n"+
				"export LANCER_REAL_%s=%q\n"+
				"exec %q shim %s \"$@\"\n",
			agent, agent, real, lancerd, agent)
		wrapper := filepath.Join(binDir, agent)
		if err := os.WriteFile(wrapper, []byte(script), 0755); err != nil {
			return fmt.Errorf("write %s wrapper: %w", agent, err)
		}
		made = append(made, agent)
	}
	if len(made) > 0 {
		fmt.Fprintf(os.Stderr, "Installed shim wrappers for: %v\n", made)
	}
	if len(skipped) > 0 {
		fmt.Fprintf(os.Stderr, "Skipped (not installed): %v\n", skipped)
	}
	fmt.Fprintf(os.Stderr,
		"To intercept terminal-started agents, put the Lancer bin FIRST on PATH:\n"+
			"  echo 'export PATH=\"$HOME/.lancer/bin:$PATH\"' >> ~/.zshrc && exec zsh\n")
	return nil
}

// lookPathExcluding resolves an executable on PATH, skipping any match inside
// excludeDir (so a shim wrapper never resolves to itself).
func lookPathExcluding(name, excludeDir string) string {
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" || dir == excludeDir {
			continue
		}
		cand := filepath.Join(dir, name)
		if fi, err := os.Stat(cand); err == nil && !fi.IsDir() && fi.Mode()&0111 != 0 {
			return cand
		}
	}
	return ""
}

// installClaudeHook drops the PreToolUse hook script to ~/.claude/hooks and
// idempotently wires it into ~/.claude/settings.json so Claude Code actually
// calls it. Without the settings wiring the interactive approval path never
// fires (Finding #10).
// ensureClaudeHookWiredOnBoot wires the Claude PreToolUse hook on daemon startup
// if it isn't already. This is what lets a plain dispatch ("Hi") launch
// immediately instead of escalating: relaxLaunchEscalation only relaxes a launch
// when the per-action hook is verifiably wired, so without this a fresh/rebranded
// install silently forces approval on every send. Idempotent and best-effort — a
// wiring failure only means more prompting, never an unintended allow.
func ensureClaudeHookWiredOnBoot() {
	home := serverHome()
	if claudeHookWired(claudeSettingsPath(home)) {
		return
	}
	if err := installClaudeHook(home); err != nil {
		fmt.Fprintf(os.Stderr, "lancerd: could not auto-wire Claude hook (sends will require approval): %v\n", err)
	}
}

func installClaudeHook(home string) error {
	scriptPath := claudeHookScriptPath(home)
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(scriptPath, []byte(claudeHookScript), 0755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", scriptPath)

	changed, err := wireClaudeHookSettings(home)
	if err != nil {
		return err
	}
	if changed {
		fmt.Fprintf(os.Stderr, "Enabled Lancer-scoped Claude approvals in %s\n", claudeSettingsPath(home))
	} else {
		fmt.Fprintf(os.Stderr, "Lancer-scoped Claude approvals already enabled in %s\n", claudeSettingsPath(home))
	}
	return nil
}

func installLaunchd(binary, home string) error {
	plistPath := launchdPlistPath(home)
	if err := os.MkdirAll(filepath.Dir(plistPath), 0755); err != nil {
		return err
	}

	// launchd jobs don't inherit the shell env that ran `lancerd install` — a
	// persistent daemon only ever sees env vars we write into its own plist.
	// APPROVAL_RELAY_SECRET is required for postApprovalPush (server.go) to
	// authenticate to push-backend's Tier-1 /approval endpoint; without it the
	// backend 401s and approval push notifications silently never reach the
	// phone (Finding: 2026-06-22 device test, recurred 2026-07-01 device test).
	//
	// PATH must include Homebrew/local bins: launchd's default PATH is
	// /usr/bin:/bin:/usr/sbin:/sbin, which cannot find `claude`/`codex`. The
	// daemon also augments PATH in-process (agentLaunchEnvironment), but
	// writing it into the plist keeps doctor/LookPath and child tools honest.
	// Do NOT put ~/.lancer/bin first — that directory holds shim wrappers that
	// dial the daemon (auth preflight must use the real vendor CLI).
	relaySecret := strings.TrimSpace(os.Getenv("APPROVAL_RELAY_SECRET"))
	if relaySecret == "" {
		relaySecret = readLaunchdRelaySecret(plistPath)
	}
	pathValue := strings.Join([]string{
		"/opt/homebrew/bin",
		"/usr/local/bin",
		filepath.Join(home, ".local", "bin"),
		"/usr/bin",
		"/bin",
		"/usr/sbin",
		"/sbin",
	}, ":")

	envEntries := []string{
		fmt.Sprintf("    <key>PATH</key><string>%s</string>", escapePlistString(pathValue)),
	}
	if relaySecret != "" {
		envEntries = append(envEntries,
			fmt.Sprintf("    <key>APPROVAL_RELAY_SECRET</key><string>%s</string>", escapePlistString(relaySecret)))
	} else {
		fmt.Fprintln(os.Stderr, "warning: APPROVAL_RELAY_SECRET is not set in this shell's environment")
		fmt.Fprintln(os.Stderr, "  and was not found in the existing launchd plist.")
		fmt.Fprintln(os.Stderr, "  Without it, the daemon's launchd job will have no way to authenticate to")
		fmt.Fprintln(os.Stderr, "  push-backend's /approval endpoint — approval push notifications will")
		fmt.Fprintln(os.Stderr, "  silently never reach your phone (only visible as HTTP 401 in")
		fmt.Fprintf(os.Stderr, "  %s).\n", filepath.Join(home, ".lancer", "lancerd.stderr.log"))
		fmt.Fprintln(os.Stderr, "  Fix: export APPROVAL_RELAY_SECRET=<value> in this shell and re-run")
		fmt.Fprintln(os.Stderr, "  `lancerd install`, or add it by hand to the generated plist's")
		fmt.Fprintf(os.Stderr, "  EnvironmentVariables dict (%s) and reload:\n", plistPath)
		fmt.Fprintf(os.Stderr, "  launchctl unload %s 2>/dev/null || true\n", plistPath)
		fmt.Fprintf(os.Stderr, "  launchctl load %s\n", plistPath)
	}
	envBlock := "  <key>EnvironmentVariables</key>\n  <dict>\n" + strings.Join(envEntries, "\n") + "\n  </dict>\n"

	plist := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.lancer.lancerd</string>
  <key>ProgramArguments</key>
  <array>
    <string>%s</string>
    <string>daemon</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
%s  <key>StandardOutPath</key><string>%s</string>
  <key>StandardErrorPath</key><string>%s</string>
</dict>
</plist>
`, binary, envBlock, filepath.Join(home, ".lancer", "lancerd.stdout.log"), filepath.Join(home, ".lancer", "lancerd.stderr.log"))
	if err := os.WriteFile(plistPath, []byte(plist), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", plistPath)
	fmt.Fprintln(os.Stderr, "Owner steps:")
	fmt.Fprintf(os.Stderr, "  launchctl unload %s 2>/dev/null || true\n", plistPath)
	fmt.Fprintf(os.Stderr, "  launchctl load %s\n", plistPath)
	return nil
}

// readLaunchdRelaySecret extracts APPROVAL_RELAY_SECRET from an existing plist
// so re-running `lancerd install` without the secret in the shell does not wipe it.
func readLaunchdRelaySecret(plistPath string) string {
	data, err := os.ReadFile(plistPath)
	if err != nil {
		return ""
	}
	const key = "<key>APPROVAL_RELAY_SECRET</key><string>"
	s := string(data)
	i := strings.Index(s, key)
	if i < 0 {
		return ""
	}
	rest := s[i+len(key):]
	j := strings.Index(rest, "</string>")
	if j < 0 {
		return ""
	}
	// Values were XML-escaped on write; reverse the common entities for reuse.
	raw := rest[:j]
	raw = strings.ReplaceAll(raw, "&lt;", "<")
	raw = strings.ReplaceAll(raw, "&gt;", ">")
	raw = strings.ReplaceAll(raw, "&quot;", "\"")
	raw = strings.ReplaceAll(raw, "&apos;", "'")
	raw = strings.ReplaceAll(raw, "&amp;", "&")
	return raw
}

// escapePlistString XML-escapes a value for safe embedding inside a plist
// <string> element. A secret shouldn't ever contain XML metacharacters, but
// this defends against a weird value breaking the generated plist.
func escapePlistString(s string) string {
	var buf bytes.Buffer
	_ = xml.EscapeText(&buf, []byte(s))
	return buf.String()
}

func installSystemd(binary, home string) error {
	unitDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(unitDir, 0755); err != nil {
		return err
	}
	unitPath := filepath.Join(unitDir, "lancerd.service")
	unit := fmt.Sprintf(`[Unit]
Description=Lancer resident bridge daemon

[Service]
ExecStart=%s daemon
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
`, binary)
	if err := os.WriteFile(unitPath, []byte(unit), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", unitPath)
	fmt.Fprintln(os.Stderr, "Owner steps:")
	fmt.Fprintln(os.Stderr, "  systemctl --user daemon-reload")
	fmt.Fprintln(os.Stderr, "  systemctl --user enable --now lancerd.service")
	if _, err := exec.LookPath("systemctl"); err == nil {
		_ = exec.Command("systemctl", "--user", "daemon-reload").Run()
	}
	return nil
}
