#!/bin/sh
# PreToolUse(Edit|Write|NotebookEdit): block direct edits to the generated Xcode project.
# Conduit.xcodeproj is gitignored and regenerated by `xcodegen` from project.yml — editing it is a
# footgun (changes vanish on the next generate). ponytail: fail-open if jq is missing.
payload=$(cat)
command -v jq >/dev/null 2>&1 || exit 0

fp=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // ""')

case "$fp" in
  *Conduit.xcodeproj/*)
    jq -n '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Conduit.xcodeproj is generated by XcodeGen from project.yml (gitignored). Edit project.yml and run `xcodegen`, not the xcodeproj."}}'
    ;;
esac
exit 0
