#!/bin/sh
# SessionStart(compact): re-state the few load-bearing facts long sessions drift on after a
# context compaction. Plain stdout is injected too, so fall back to it if jq is absent.
ctx="Lancer reminders (post-compaction):
- Verify before \"done\": LancerKit -> cd Packages/LancerKit && swift test; iOS UI / app-shell / strict-concurrency -> XcodeBuildMCP app-target build (plain swift build skips #if os(iOS)); daemon -> go build/vet/test ./... per module. State the command output as evidence.
- Lancer.xcodeproj is generated by XcodeGen -- edit project.yml, not the xcodeproj.
- V1 transport is the E2E relay (phone <-> Cloud Run push-backend <-> resident lancerd); SSH is the fallback.
- Don't revert uncommitted git changes (other agents' / owner's work). Never commit secrets."

if command -v jq >/dev/null 2>&1; then
  printf '%s' "$ctx" | jq -Rs '{hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:.}}'
else
  printf '%s\n' "$ctx"
fi
exit 0
