#if os(iOS)
import SwiftUI
import UIKit
import AccountKit
import DesignSystem
import LancerCore
import SecurityKit
import SSHTransport

// MARK: - OnboardingRedesignView (productized 3-step first-run)

/// First-run onboarding in the simplified 3-step language: Why Lancer → Pair the
/// bridge → Default policy. Pairing is real (drives the app-wide `E2ERelayClient`
/// with a real 6-digit code); the chosen policy tier is persisted and pushed to the
/// daemon on first connect via `OnboardingPolicy`.
///
/// Visuals follow the editorial onboarding board, but the first screen now proves
/// the actual product loop before asking the user to pair a machine.
public struct OnboardingRedesignView: View {
    let onContinue: () -> Void
    let onPaired: ((E2ERelayClient, RelayMachineRecord) -> Void)?

    @StateObject private var client: E2ERelayClient
    private let accountSession: AccountSessionController?
    @State private var step: Int
    @State private var selectedLevel: OnboardingCautionLevel = .balanced
    // Relay pairing: the code is generated by the DESKTOP (`lancerd pair`) and
    // typed in here — the phone never invents its own. Code-only: no QR scan path.
    @State private var manualCode = ""
    @State private var pairingMessage: String?
    @State private var showDeviceBindingScanner = false
    @State private var deviceBindingMessage: String?
    @State private var deviceBindingIsError = false

    @AppStorage("lancer.onboarding.autonomyPreset") private var storedPreset: String = ""
    @Environment(\.lancerTokens) private var t
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    private let steps = OnboardingRedesignStep.all

    public init(
        onContinue: @escaping () -> Void,
        accountSession: AccountSessionController? = nil,
        startStep: Int = 0,
        onPaired: ((E2ERelayClient, RelayMachineRecord) -> Void)? = nil
    ) {
        self.onContinue = onContinue
        self.accountSession = accountSession
        self.onPaired = onPaired
        let resolved = E2ERelayClient(
            relayURL: RelaySettings.url(),
            pairingCode: PairingCrypto.generatePairingCode()
        )
        _client = StateObject(wrappedValue: resolved)
        _step = State(initialValue: min(max(startStep, 0), OnboardingRedesignStep.all.count - 1))
    }

    private var current: OnboardingRedesignStep { steps[step] }

    private var pairingPresentation: PairingPresentationState {
        PairingPresentationState(
            pairing: client.pairingState,
            connection: client.connectionState,
            skipWarning: pairingMessage
        )
    }

    /// True while the account-creation gate is showing instead of the current step's
    /// own content. Computed once and reused by both `content` and `footer` below so
    /// the two can never disagree about which branch is active.
    private var isAccountGateActive: Bool {
        current.kind != .value && current.kind != .pair && accountSession != nil && accountSession?.mode == nil
    }

    public var body: some View {
        // Every onboarding screen — carousel steps, the account gate, SSH setup — renders
        // through the same scaffold so the back chevron and step dots never disappear or
        // shift between screens (previously the account gate and SSH setup each drew their
        // own ad-hoc header with no back affordance at all).
        OnboardingScaffold(
            stepIndex: step,
            totalSteps: steps.count,
            leading: step > 0 ? .back : .none,
            topBarStyle: current.kind == .value ? .hero : .page,
            onLeading: {
                guard step > 0 else { return }
                withAnimation(LancerMotion.resolved(.smooth(duration: 0.28, extraBounce: 0), reduceMotion: reduceMotion)) { step -= 1 }
            }
        ) {
            // Account creation gates everything after the relay pairing step.
            if isAccountGateActive, let accountSession {
                AccountEntryView(account: accountSession, onComplete: advanceAfterAccount)
            } else {
                ScrollView(.vertical, showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 0) {
                        // Full-bleed — NOT inside the 560pt content constraint below, or
                        // the hero stops spanning the full width on iPad/wide screens.
                        OnboardingHeroBanner(
                            eyebrow: current.eyebrow,
                            title: current.title,
                            subtitle: current.body,
                            compact: current.kind == .value || current.kind == .pair
                        )
                        primaryBlock
                            .frame(maxWidth: 560, alignment: .leading)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.top, 24)
                            .padding(.bottom, 24)
                    }
                }
            }
        } footer: {
            // The account gate renders its own CTA inline as content (sign-in/sign-up
            // buttons) — only the carousel steps use the scaffold's dedicated footer slot.
            if !isAccountGateActive {
                OnboardingFooter {
                    VStack(spacing: 10) {
                        DSButton(
                            current.ctaArrow ? "\(current.primaryAction) →" : current.primaryAction,
                            variant: .primary, size: .lg, fullWidth: true,
                            action: advanceOrFinish
                        )
                        .disabled(current.kind == .pair && pairingPresentation.disablesPrimaryAction)
                        .accessibilityIdentifier("onboardingPrimary")

                        // A real, always-tappable skip — not just the warn-then-tap-again
                        // path on the primary button above, which isn't discoverable.
                        if current.kind == .pair, client.pairingState != .paired {
                            Button("Skip for now", action: skipPairing)
                                .font(.dsSansPt(13, weight: .medium))
                                .foregroundStyle(t.text3)
                                .accessibilityIdentifier("onboardingSkipPairing")
                        }
                    }
                }
            }
        }
        .dynamicTypeSize(...DynamicTypeSize.accessibility3)
        .onChange(of: client.pairingState) { _, state in
            guard state == .paired, let onPaired else { return }
            onPaired(client, RelayMachineRecord(id: client.machineID, displayName: "Relay host", pairedAt: .now))
        }
        .sheet(isPresented: $showDeviceBindingScanner) {
            OnboardingScanScreen(
                onScan: { payload in
                    showDeviceBindingScanner = false
                    bindAccountDevice(scannedPayload: payload)
                },
                onUnavailable: { reason in
                    showDeviceBindingScanner = false
                    deviceBindingMessage = reason
                    deviceBindingIsError = true
                    Haptics.warning()
                },
                onEnterCodeInstead: {
                    showDeviceBindingScanner = false
                    deviceBindingMessage = "Use the QR scanner on a physical device to bind a daemon."
                    deviceBindingIsError = true
                }
            )
        }
    }


    // MARK: Per-step primary block

    @ViewBuilder
    private var primaryBlock: some View {
        switch current.kind {
        case .value:
            VStack(alignment: .leading, spacing: 0) {
                OnboardingProductProofPreview()
                    .padding(.horizontal, 24)
                    .padding(.top, 2)
            }
        case .pair:
            VStack(alignment: .leading, spacing: 18) {
                OnboardingPairingBlock(
                    client: client,
                    manualCode: $manualCode,
                    presentation: pairingPresentation,
                    onSubmitCode: { code in applyPairingCode(code, relay: nil) },
                    canBindAccountDevice: accountSession?.isStandardAccount == true,
                    deviceBindingMessage: deviceBindingMessage,
                    deviceBindingIsError: deviceBindingIsError,
                    onBindAccountDevice: { showDeviceBindingScanner = true }
                )
                    .padding(.horizontal, 24)
            }
        case .policy:
            OnboardingPolicyCards(selectedLevel: $selectedLevel).padding(.horizontal, 24)
        }
    }

    // MARK: Actions

    private func advanceOrFinish() {
        // "Pair & continue" previously advanced unconditionally, so a user could
        // finish onboarding having never actually paired a machine — landing on an
        // empty Home with no way back to the code field. First tap while unpaired
        // shows a real warning (reusing `pairingMessage`, previously wired but never
        // set) instead of silently proceeding; a second tap explicitly skips.
        if current.kind == .pair, client.pairingState != .paired, pairingMessage == nil {
            pairingMessage = "No machine paired yet. Tap Pair & continue again to skip for now — you can pair later from Settings."
            Haptics.warning()
            return
        }
        if step < steps.count - 1 {
            Haptics.selection()
            withAnimation(LancerMotion.resolved(.smooth(duration: 0.28, extraBounce: 0), reduceMotion: reduceMotion)) { step += 1 }
        } else {
            finish()
        }
    }

    /// A dedicated, always-visible "Skip for now" affordance for the pairing step —
    /// tapping it already states the intent, so unlike `advanceOrFinish` it doesn't
    /// need the warn-then-repeat-tap pattern first.
    private func skipPairing() {
        Haptics.selection()
        pairingMessage = nil
        if step < steps.count - 1 {
            withAnimation(LancerMotion.resolved(.smooth(duration: 0.28, extraBounce: 0), reduceMotion: reduceMotion)) { step += 1 }
        } else {
            finish()
        }
    }

    private func advanceAfterAccount() {
        Haptics.success()
        // AccountEntry only appears once the user tries to move past relay pairing.
        // Defensive no-op in the normal flow since step
        // is already wherever the user was heading; guards a fresh/resumed session
        // that could otherwise land here with step still at 0.
        if step < 2 {
            step = min(2, steps.count - 1)
        }
    }

    /// Connect to the relay using the DESKTOP's pairing code, typed in here. Starts
    /// a fresh keypair, then connects. `connect()` is idempotent, so re-entry
    /// (retype) cleanly replaces the channel.
    private func applyPairingCode(_ code: String, relay: URL?) {
        guard code.count == 6 else { return }
        pairingMessage = nil                // clear any stale skip-warning
        client.beginPairingSession()        // fresh keypair for this attempt
        client.relayURL = relay ?? RelaySettings.url()
        client.pairingCode = code
        client.connect()
        Haptics.selection()
    }

    private func finish() {
        finishOnboarding()
    }

    /// Persist the chosen policy tier and leave onboarding.
    private func finishOnboarding() {
        storedPreset = selectedLevel.mappedPreset.rawValue
        // Push this tier's starter policy on the first daemon connect (see OnboardingPolicy).
        OnboardingPolicy.markPending(selectedLevel)
        Haptics.success()
        onContinue()
    }

    private func bindAccountDevice(scannedPayload: String) {
        guard let challenge = OnboardingPairing.extractDeviceBinding(fromScanned: scannedPayload) else {
            deviceBindingMessage = "That QR code can pair the relay, but it is not an account device-binding challenge."
            deviceBindingIsError = true
            Haptics.error()
            return
        }
        guard let accountSession else { return }
        Task {
            do {
                try await accountSession.bindDaemonDevice(
                    challengeID: challenge.challengeID,
                    secret: challenge.secret,
                    backendURL: challenge.backendURL
                )
                deviceBindingMessage = "Device authorized. The daemon will finish binding without your password."
                deviceBindingIsError = false
                Haptics.success()
            } catch {
                deviceBindingMessage = "Couldn't authorize this device. Check the account session and try again."
                deviceBindingIsError = true
                Haptics.error()
            }
        }
    }
}

// MARK: - Step "value" · product proof

private struct OnboardingProductProofPreview: View {
    @Environment(\.lancerTokens) private var t

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                Text("WHAT YOU'LL SEE")
                    .font(.dsMonoPt(10, weight: .medium))
                    .tracking(1.2)
                    .foregroundStyle(t.text4)
                Spacer()
                Text("preview")
                    .font(.dsSansPt(11, weight: .medium))
                    .foregroundStyle(t.text4)
            }

            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .fill(t.surface.opacity(0.72))
                .aspectRatio(1.12, contentMode: .fit)
                .overlay(
                    RoundedRectangle(cornerRadius: 24, style: .continuous)
                        .strokeBorder(t.borderStrong.opacity(0.75), style: StrokeStyle(lineWidth: 1, dash: [7, 7]))
                )
                .overlay(alignment: .bottomTrailing) {
                    Text("5 sec loop")
                        .font(.dsMonoPt(10, weight: .medium))
                        .tracking(0.8)
                        .foregroundStyle(t.text4)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 6)
                        .background(t.surface2, in: Capsule())
                        .padding(14)
                }
            .background(t.surface, in: RoundedRectangle(cornerRadius: 20, style: .continuous))
            .overlay(RoundedRectangle(cornerRadius: 20, style: .continuous).strokeBorder(t.border, lineWidth: 1))
            .shadow(color: .black.opacity(0.07), radius: 14, x: 0, y: 7)
        }
        .accessibilityElement(children: .ignore)
        .accessibilityLabel("Empty preview frame reserved for a five second onboarding animation.")
    }
}

// MARK: - Step "pair" · pairing

private enum PairingMessageTone {
    case neutral
    case success
    case warning
    case error
}

private struct PairingPresentationState {
    let title: String
    let detail: String?
    let tone: PairingMessageTone
    let fieldTone: PairingMessageTone
    let showsProgress: Bool
    let disablesPrimaryAction: Bool

    init(
        pairing: E2ERelayClient.PairingState,
        connection: E2ERelayClient.ConnectionState,
        skipWarning: String?
    ) {
        if let skipWarning {
            title = skipWarning
            detail = "Pairing is still recommended. You can also pair later from Settings."
            tone = .warning
            fieldTone = .warning
            showsProgress = false
            disablesPrimaryAction = false
            return
        }

        switch pairing {
        case .paired:
            title = "Paired."
            detail = "This phone can now reach your machine over the encrypted relay."
            tone = .success
            fieldTone = .success
            showsProgress = false
            disablesPrimaryAction = false
        case .waitingForPeer:
            title = "Waiting for your desktop."
            detail = "Keep `lancerd pair` open until the relay confirms both sides."
            tone = .neutral
            fieldTone = .neutral
            showsProgress = true
            // Not disabled: if the desktop side never confirms (stale code, wrong
            // network, or — on a device that's paired before — a stale reconnect
            // attempt using old credentials) the button must stay tappable so the
            // existing warn-then-skip flow in advanceOrFinish() can run. A disabled
            // button here was a dead end with no way back to Home.
            disablesPrimaryAction = false
        case .pairingFailed(let reason):
            title = Self.failureMessage(for: reason)
            detail = Self.failureRecovery(for: reason)
            tone = .error
            fieldTone = .error
            showsProgress = false
            disablesPrimaryAction = false
        case .unpaired:
            switch connection {
            case .connecting, .reconnecting:
                title = "Connecting to the relay."
                detail = "Keep the code visible on your machine."
                tone = .neutral
                fieldTone = .neutral
                showsProgress = true
                // See the .waitingForPeer case above — stays tappable so a stuck
                // connection attempt never fully blocks the skip path.
                disablesPrimaryAction = false
            case .connected:
                title = "Enter the code from your machine."
                detail = nil
                tone = .neutral
                fieldTone = .neutral
                showsProgress = false
                disablesPrimaryAction = false
            case .disconnected:
                title = "Enter the code from your machine."
                detail = nil
                tone = .neutral
                fieldTone = .neutral
                showsProgress = false
                disablesPrimaryAction = false
            }
        }
    }

    static func failureMessage(for reason: String) -> String {
        let lower = reason.lowercased()
        if lower.contains("expired") {
            return "That code expired."
        }
        if lower.contains("mismatch") {
            return "That code didn't match."
        }
        if lower.contains("too many") || lower.contains("rate limit") {
            return "Too many attempts."
        }
        return "Couldn't connect to your machine."
    }

    static func failureRecovery(for reason: String) -> String {
        let lower = reason.lowercased()
        if lower.contains("expired") {
            return "Run `lancerd pair` again and enter the new code."
        }
        if lower.contains("mismatch") {
            return "Check the digits and try again. Your code stays here."
        }
        if lower.contains("too many") || lower.contains("rate limit") {
            return "Wait a minute, then try the same flow again."
        }
        return "Check that your machine and phone are online, then try again."
    }
}

private struct OnboardingPairingBlock: View {
    @ObservedObject var client: E2ERelayClient
    @Binding var manualCode: String
    let presentation: PairingPresentationState
    let onSubmitCode: (String) -> Void
    let canBindAccountDevice: Bool
    let deviceBindingMessage: String?
    let deviceBindingIsError: Bool
    let onBindAccountDevice: () -> Void

    @Environment(\.lancerTokens) private var t
    @FocusState private var codeFocused: Bool
    @State private var didCopyInstallCommand = false

    private static let installCommand = "curl -fsSL https://storage.googleapis.com/conduit-dist-f1c2466d/install.sh | sh"
    // Placeholder — swap for the real marketing/download page once it exists.
    private static let downloadPageURL = URL(string: "https://lancersoftware.dev/download")!

    // The pairing card assumes lancerd is already installed — a first-time user
    // has no way to get it without leaving the app. This is the one V1 escape
    // hatch: copy the real install one-liner (docs/daemon/lancerd/INSTALL.md)
    // straight to the clipboard so they can paste it into Terminal.
    private var installCommandRow: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Don't have lancerd yet?")
                .font(.dsSansPt(11.5, weight: .semibold))
                .foregroundStyle(t.text3)
            Button {
                UIPasteboard.general.string = Self.installCommand
                Haptics.success()
                didCopyInstallCommand = true
                Task {
                    try? await Task.sleep(for: .seconds(2))
                    didCopyInstallCommand = false
                }
            } label: {
                HStack(spacing: 8) {
                    Text(Self.installCommand)
                        .font(.dsMonoPt(10.5))
                        .foregroundStyle(t.text2)
                        .lineLimit(1)
                        .truncationMode(.middle)
                    Spacer(minLength: 8)
                    DSIconView(didCopyInstallCommand ? .check : .copy, size: 13, color: t.text3)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 8)
                .background(t.surface, in: RoundedRectangle(cornerRadius: 10, style: .continuous))
                .overlay(RoundedRectangle(cornerRadius: 10, style: .continuous).strokeBorder(t.border, lineWidth: 1))
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Copy lancerd install command")
            Text(didCopyInstallCommand ? "Copied — paste into Terminal on your machine." : "Copies a one-line installer. Runs on macOS or Linux.")
                .font(.dsSansPt(10.5))
                .foregroundStyle(t.text4)
            DSLink("or download from the website", size: 10.5) {
                UIApplication.shared.open(Self.downloadPageURL)
            }
        }
        .padding(.top, 4)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            VStack(alignment: .leading, spacing: 10) {
                Text("ON YOUR MACHINE")
                    .font(.dsMonoPt(10, weight: .medium))
                    .tracking(1.2)
                    .foregroundStyle(t.text4)

                Text("Run `lancerd pair`, then enter the 6-digit code it prints.")
                    .font(.dsSansPt(13, weight: .medium))
                    .foregroundStyle(t.text2)
                    .fixedSize(horizontal: false, vertical: true)

                TextField("000000", text: $manualCode)
                    .keyboardType(.numberPad)
                    .font(.dsDisplayPt(26, weight: .bold))
                    .multilineTextAlignment(.center)
                    .tracking(8)
                    .focused($codeFocused)
                    .onChange(of: manualCode) { _, v in
                        let digits = String(v.filter(\.isNumber).prefix(6))
                        if digits != v { manualCode = digits }
                        if digits.count == 6 { codeFocused = false; onSubmitCode(digits) }
                    }
                    .padding(.vertical, 12)
                    .frame(maxWidth: .infinity)
                    .background(fieldFill, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                    .overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).strokeBorder(fieldBorder, lineWidth: 1.5))
                    .accessibilityIdentifier("pairingCodeField")

                inlineStatus

                Text("Codes expire in a few minutes, work once, and should not be shared.")
                    .font(.dsSansPt(11.5))
                    .foregroundStyle(t.text4)
                    .fixedSize(horizontal: false, vertical: true)

                installCommandRow
            }
            .padding(14)
            .background(t.surface2, in: RoundedRectangle(cornerRadius: 18, style: .continuous))
            .overlay(RoundedRectangle(cornerRadius: 18, style: .continuous).strokeBorder(fieldGroupBorder, lineWidth: 1))

            if canBindAccountDevice {
                Button(action: onBindAccountDevice) {
                    Label("link this machine to my account", systemImage: "qrcode.viewfinder")
                        .font(.dsSansPt(13, weight: .semibold))
                        .foregroundStyle(t.accent)
                        .frame(maxWidth: .infinity)
                        .padding(.top, 8)
                }
                .buttonStyle(.plain)
                .accessibilityIdentifier("accountDeviceBinding")
                Text("Scans a one-time security code. Lancer never asks for your account password on this machine.")
                    .font(.dsSansPt(11.5))
                    .foregroundStyle(t.text4)
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
                if let deviceBindingMessage {
                    Text(deviceBindingMessage)
                        .font(.dsSansPt(12, weight: .medium))
                        .foregroundStyle(deviceBindingIsError ? t.danger : t.ok)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: .infinity)
                }
            }
        }
        .onChange(of: client.pairingState) { _, state in
            switch state {
            case .paired:        Haptics.success()
            case .pairingFailed: Haptics.error()
            case .unpaired, .waitingForPeer: break
            }
        }
    }

    @ViewBuilder
    private var inlineStatus: some View {
        HStack(alignment: .top, spacing: 8) {
            if presentation.showsProgress {
                ProgressView()
                    .controlSize(.small)
                    .padding(.top, 1)
            } else {
                Image(systemName: statusSymbol)
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(statusColor)
                    .padding(.top, 2)
            }
            VStack(alignment: .leading, spacing: 2) {
                Text(presentation.title)
                    .font(.dsSansPt(12.5, weight: .semibold))
                    .foregroundStyle(statusColor)
                    .fixedSize(horizontal: false, vertical: true)
                if let detail = presentation.detail {
                    Text(detail)
                        .font(.dsSansPt(11.5))
                        .foregroundStyle(t.text3)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            Spacer(minLength: 0)
        }
    }

    private var statusSymbol: String {
        switch presentation.tone {
        case .success: return "checkmark.circle.fill"
        case .warning: return "exclamationmark.triangle.fill"
        case .error: return "xmark.circle.fill"
        case .neutral: return "info.circle.fill"
        }
    }

    private var statusColor: Color {
        switch presentation.tone {
        case .success: return t.ok
        case .warning: return t.warn
        case .error: return t.danger
        case .neutral: return t.text4
        }
    }

    private var fieldBorder: Color {
        if codeFocused { return t.accent }
        switch presentation.fieldTone {
        case .success: return t.ok
        case .warning: return t.warn
        case .error: return t.danger
        case .neutral: return t.border
        }
    }

    private var fieldFill: Color {
        switch presentation.fieldTone {
        case .success: return t.okSoft
        case .warning: return t.warnSoft
        case .error: return t.dangerSoft
        case .neutral: return t.surface
        }
    }

    private var fieldGroupBorder: Color {
        switch presentation.fieldTone {
        case .success: return t.ok.opacity(0.5)
        case .warning: return t.warn.opacity(0.55)
        case .error: return t.danger.opacity(0.6)
        case .neutral: return t.border
        }
    }
}

// MARK: - Step 2 · policy cards

private struct OnboardingPolicyCards: View {
    @Binding var selectedLevel: OnboardingCautionLevel

    @Environment(\.lancerTokens) private var t
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        VStack(spacing: 11) {
            ForEach(OnboardingCautionLevel.allCases) { level in
                let isSelected = selectedLevel == level
                Button {
                    Haptics.selection()
                    withAnimation(LancerMotion.resolved(.smooth(duration: 0.18, extraBounce: 0), reduceMotion: reduceMotion)) {
                        selectedLevel = level
                    }
                } label: {
                    HStack(spacing: 13) {
                        ZStack {
                            Circle()
                                .strokeBorder(isSelected ? t.accent : t.borderStrong, lineWidth: 2)
                                .frame(width: 24, height: 24)
                            Circle()
                                .fill(isSelected ? t.accent : .clear)
                                .frame(width: 9, height: 9)
                        }
                        VStack(alignment: .leading, spacing: 1) {
                            Text(level.title).font(.dsDisplayPt(16, weight: .bold)).foregroundStyle(t.text)
                            Text(level.detail).font(.dsSansPt(12.5)).foregroundStyle(t.text4)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        Spacer(minLength: 0)
                    }
                    .padding(15)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(
                        RoundedRectangle(cornerRadius: 16, style: .continuous).fill(t.surface)
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: 16, style: .continuous)
                            .strokeBorder(isSelected ? t.accent : t.border, lineWidth: 1.5)
                    )
                    .shadow(color: .black.opacity(isSelected ? 0.16 : 0.05), radius: isSelected ? 14 : 3, x: 0, y: isSelected ? 6 : 1)
                }
                .buttonStyle(.plain)
                .accessibilityIdentifier("policyPreset_\(level.rawValue)")
                .accessibilityValue(isSelected ? "selected" : "unselected")
            }
        }
    }
}

// MARK: - Step model

private struct OnboardingRedesignStep: Identifiable {
    enum Kind { case value, pair, policy }

    let id: String
    let eyebrow: String
    let title: String
    let body: String
    let primaryAction: String
    let ctaArrow: Bool
    let kind: Kind

    static let all: [OnboardingRedesignStep] = [
        .init(
            id: "value",
            eyebrow: "lancer",
            title: "Steer AI coding agents from your phone.",
            body: "Pair this phone with your machine, review risky actions, and keep work moving without opening a laptop.",
            primaryAction: "Continue",
            ctaArrow: true,
            kind: .value
        ),
        .init(
            id: "pair",
            eyebrow: "pair this phone",
            title: "Connect to your machine.",
            body: "Run one command on your machine, then enter the code here. Lancer keeps the relay encrypted end to end.",
            primaryAction: "Pair & continue",
            ctaArrow: false,
            kind: .pair
        ),
        .init(
            id: "policy",
            eyebrow: "almost there",
            title: "How cautious should agents be?",
            body: "Set how freely agents act. You can fine-tune this per machine later.",
            primaryAction: "Continue",
            ctaArrow: true,
            kind: .policy
        ),
    ]
}

#Preview("Onboarding redesign") {
    OnboardingRedesignView(onContinue: {})
        .environment(\.lancerTokens, .light)
}
#endif
