#if os(iOS)
import SwiftUI
import AccountKit
import DesignSystem
import LancerCore
import SecurityKit
import SSHTransport

// MARK: - OnboardingRedesignView (productized 3-step first-run)

/// First-run onboarding in the simplified 3-step language: Why Lancer → Pair the
/// bridge → Default policy. Pairing is real (drives the app-wide `E2ERelayClient`
/// with a real 6-digit code); the chosen policy tier is persisted and pushed to the
/// daemon on first connect via `OnboardingPolicy`.
///
/// Visuals are a faithful reproduction of the `Lancer App.dc.html` onboarding board:
/// a terracotta editorial hero (grid texture + lavender pixel mark, Instrument Serif
/// italic kicker over a Bricolage display title), then a per-step block — value rows,
/// pairing digit-boxes, or policy cards — with a black/orange CTA and an always-present
/// "I've already set up Lancer" link.
public struct OnboardingRedesignView: View {
    let onContinue: () -> Void
    let onAlreadyUseLancer: () -> Void
    let onSetupWorkspace: () -> Void
    /// Optional: finish onboarding and route the user to "Add a machine" (SSH).
    /// Provided by the app shell; when nil the SSH step's primary action just
    /// finishes onboarding like Skip.
    let onEnableSSH: (() -> Void)?

    @StateObject private var client: E2ERelayClient
    private let accountSession: AccountSessionController?
    @State private var step: Int
    @State private var selectedLevel: OnboardingCautionLevel = .balanced
    // Relay pairing: the code is generated by the DESKTOP (`lancerd pair`) and
    // either scanned from its QR or typed in here — the phone never invents its own.
    @State private var manualCode = ""
    @State private var showPairingScanner = false
    @State private var pairingMessage: String?
    @State private var showDeviceBindingScanner = false
    @State private var deviceBindingMessage: String?
    @State private var deviceBindingIsError = false

    @AppStorage("lancer.onboarding.autonomyPreset") private var storedPreset: String = ""
    @Environment(\.lancerTokens) private var t
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    private let steps = OnboardingRedesignStep.all

    public init(
        onContinue: @escaping () -> Void,
        onAlreadyUseLancer: @escaping () -> Void = {},
        onSetupWorkspace: @escaping () -> Void = {},
        onEnableSSH: (() -> Void)? = nil,
        relayClient: E2ERelayClient? = nil,
        accountSession: AccountSessionController? = nil,
        startStep: Int = 0
    ) {
        self.onContinue = onContinue
        self.onAlreadyUseLancer = onAlreadyUseLancer
        self.onSetupWorkspace = onSetupWorkspace
        self.onEnableSSH = onEnableSSH
        self.accountSession = accountSession
        let resolved = relayClient ?? E2ERelayClient(
            relayURL: RelaySettings.url(),
            pairingCode: PairingCrypto.generatePairingCode()
        )
        _client = StateObject(wrappedValue: resolved)
        _step = State(initialValue: min(max(startStep, 0), OnboardingRedesignStep.all.count - 1))
    }

    private var current: OnboardingRedesignStep { steps[step] }

    public var body: some View {
        Group {
            // Start with the product value. Account creation follows the first
            // screen so people understand why Lancer asks for identity details.
            if current.kind != .value, let accountSession, accountSession.mode == nil {
                AccountEntryView(account: accountSession, onComplete: advanceAfterAccount)
            } else if current.kind == .sshSetup {
                // The optional SSH step renders its own header + CTAs (no shared
                // hero/footer), so present it standalone like the account gate.
                OnboardingSSHSetupScreen(
                    onAddHost: { finishOnboarding(routeToAddHost: true) },
                    onSkip: { finishOnboarding(routeToAddHost: false) }
                )
            } else {
                VStack(spacing: 0) {
                    hero
                    ScrollView(.vertical, showsIndicators: false) {
                        primaryBlock
                            .frame(maxWidth: 560, alignment: .leading)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.top, 24)
                            .padding(.bottom, 24)
                    }
                    footer
                }
            }
        }
        .background(t.bg.ignoresSafeArea())
        .dynamicTypeSize(...DynamicTypeSize.accessibility3)
        // Relay pairing: scan the desktop's `lancerd pair` QR, or type its code.
        .sheet(isPresented: $showPairingScanner) {
            OnboardingScanScreen(
                onScan: { payload in
                    showPairingScanner = false
                    if let pairing = OnboardingPairing.extractPairing(fromScanned: payload) {
                        pairingMessage = nil
                        applyPairingCode(pairing.code, relay: pairing.relay)
                    } else {
                        pairingMessage = "That QR isn't a Lancer pairing code. Run `lancerd pair` on your machine."
                        Haptics.error()
                    }
                },
                onUnavailable: { reason in
                    showPairingScanner = false
                    // Simulator/no-camera: fall back to the manual 6-digit field.
                    pairingMessage = reason
                },
                onEnterCodeInstead: { showPairingScanner = false }
            )
        }
        .sheet(isPresented: $showDeviceBindingScanner) {
            OnboardingScanScreen(
                onScan: { payload in
                    showDeviceBindingScanner = false
                    bindAccountDevice(scannedPayload: payload)
                },
                onUnavailable: { reason in
                    showDeviceBindingScanner = false
                    deviceBindingMessage = reason
                    deviceBindingIsError = true
                    Haptics.warning()
                },
                onEnterCodeInstead: {
                    showDeviceBindingScanner = false
                    deviceBindingMessage = "Use the QR scanner on a physical device to bind a daemon."
                    deviceBindingIsError = true
                }
            )
        }
    }

    // MARK: Hero (terracotta editorial header — shared across steps)

    private var hero: some View {
        VStack(alignment: .leading, spacing: 0) {
            headerRow
                .padding(.horizontal, 26)
                .padding(.top, 6)

            VStack(alignment: .leading, spacing: 0) {
                OnboardingBrandMark()
                    .padding(.bottom, 18)
                Text(current.eyebrow)
                    .font(.dsEditorialPt(20))
                    .foregroundStyle(OnboardingPalette.heroKicker)
                Text(current.title)
                    .font(.dsDisplayPt(34, weight: .heavy))
                    .tracking(-1)
                    .foregroundStyle(.white)
                    .lineLimit(2)
                    .minimumScaleFactor(0.85)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.top, 5)
                Text(current.body)
                    .font(.dsSansPt(13))
                    .lineSpacing(3)
                    .foregroundStyle(.white.opacity(0.88))
                    .fixedSize(horizontal: false, vertical: true)
                    .frame(maxWidth: 292, alignment: .leading)
                    .padding(.top, 12)
            }
            .padding(.horizontal, 28)
            .padding(.top, 22)
        }
        .padding(.bottom, 28)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(heroBackground.ignoresSafeArea(edges: .top))
    }

    private var heroBackground: some View {
        ZStack(alignment: .bottomTrailing) {
            LinearGradient(colors: [t.accent, t.accentInk], startPoint: .topLeading, endPoint: .bottomTrailing)
            Canvas { ctx, size in
                var y: CGFloat = 0
                while y <= size.height {
                    ctx.fill(Path(CGRect(x: 0, y: y, width: size.width, height: 1)),
                             with: .color(.white.opacity(0.05)))
                    y += 30
                }
            }
            Circle()
                .fill(.white.opacity(0.07))
                .frame(width: 190, height: 190)
                .offset(x: 34, y: 46)
        }
        .clipShape(UnevenRoundedRectangle(bottomLeadingRadius: 34, bottomTrailingRadius: 34, style: .continuous))
    }

    private var headerRow: some View {
        HStack(spacing: 9) {
            Button {
                guard step > 0 else { return }
                withAnimation(LancerMotion.resolved(.smooth(duration: 0.28, extraBounce: 0), reduceMotion: reduceMotion)) { step -= 1 }
            } label: {
                Image(systemName: "chevron.left")
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundStyle(.white)
                    .frame(width: 14)
            }
            .buttonStyle(.plain)
            .opacity(step > 0 ? 1 : 0)
            .disabled(step == 0)
            .accessibilityLabel("Back")
            .accessibilityIdentifier("onboardingBack")

            ForEach(0..<steps.count, id: \.self) { i in
                Capsule(style: .continuous)
                    .fill(i <= step ? Color.white : Color.white.opacity(0.4))
                    .frame(width: i == step ? 22 : 7, height: 7)
                    .animation(reduceMotion ? nil : .easeOut(duration: 0.3), value: step)
            }

            Spacer(minLength: 0)
        }
        .frame(height: 20)
    }

    // MARK: Per-step primary block

    @ViewBuilder
    private var primaryBlock: some View {
        switch current.kind {
        case .value:
            OnboardingValueRows().padding(.horizontal, 28).padding(.top, 12)
        case .pair:
            OnboardingPairingBlock(
                client: client,
                manualCode: $manualCode,
                pairingMessage: pairingMessage,
                onScan: { showPairingScanner = true },
                onSubmitCode: { code in applyPairingCode(code, relay: nil) },
                canBindAccountDevice: accountSession?.isStandardAccount == true,
                deviceBindingMessage: deviceBindingMessage,
                deviceBindingIsError: deviceBindingIsError,
                onBindAccountDevice: { showDeviceBindingScanner = true }
            )
                .padding(.horizontal, 24)
        case .policy:
            OnboardingPolicyCards(selectedLevel: $selectedLevel).padding(.horizontal, 24)
        case .sshSetup:
            // Rendered standalone from `body` (its own chrome); never shown here.
            EmptyView()
        }
    }

    // MARK: Footer CTA

    private var footer: some View {
        VStack(spacing: 11) {
            DSButton(
                current.ctaArrow ? "\(current.primaryAction) →" : current.primaryAction,
                variant: .primary,
                size: .lg,
                fullWidth: true,
                action: advanceOrFinish
            )
            .accessibilityIdentifier("onboardingPrimary")
        }
        .padding(.horizontal, 24)
        .padding(.top, 14)
        .padding(.bottom, 16)
        .background(t.bg.ignoresSafeArea(edges: .bottom))
    }

    // MARK: Actions

    private func advanceOrFinish() {
        if step < steps.count - 1 {
            Haptics.selection()
            withAnimation(LancerMotion.resolved(.smooth(duration: 0.28, extraBounce: 0), reduceMotion: reduceMotion)) { step += 1 }
        } else {
            finish()
        }
    }

    private func advanceAfterAccount() {
        Haptics.success()
        // AccountEntry only appears after the value screen. Keep the pair step
        // selected rather than requiring an extra, anonymous onboarding state.
        if step == 0 {
            step = min(1, steps.count - 1)
        }
    }

    /// Connect to the relay using the DESKTOP's pairing code (from a scanned QR or
    /// typed in). Starts a fresh keypair, adopts the QR's relay URL when present
    /// (self-hosters) else the shipped relay, then connects. `connect()` is
    /// idempotent, so re-entry (rescan / retype) cleanly replaces the channel.
    private func applyPairingCode(_ code: String, relay: URL?) {
        guard code.count == 6 else { return }
        client.beginPairingSession()        // fresh keypair for this attempt
        client.relayURL = relay ?? RelaySettings.url()
        client.pairingCode = code
        client.connect()
        Haptics.selection()
    }

    private func finish() {
        finishOnboarding(routeToAddHost: false)
    }

    /// Persist the chosen policy tier and leave onboarding. When `routeToAddHost`
    /// and the app shell supplied `onEnableSSH`, route the user straight to "Add a
    /// machine"; otherwise just enter the app.
    private func finishOnboarding(routeToAddHost: Bool) {
        storedPreset = selectedLevel.mappedPreset.rawValue
        // Push this tier's starter policy on the first daemon connect (see OnboardingPolicy).
        OnboardingPolicy.markPending(selectedLevel)
        Haptics.success()
        if routeToAddHost, let onEnableSSH { onEnableSSH() } else { onContinue() }
    }

    private func bindAccountDevice(scannedPayload: String) {
        guard let challenge = OnboardingPairing.extractDeviceBinding(fromScanned: scannedPayload) else {
            deviceBindingMessage = "That QR code can pair the relay, but it is not an account device-binding challenge."
            deviceBindingIsError = true
            Haptics.error()
            return
        }
        guard let accountSession else { return }
        Task {
            do {
                try await accountSession.bindDaemonDevice(
                    challengeID: challenge.challengeID,
                    secret: challenge.secret,
                    backendURL: challenge.backendURL
                )
                deviceBindingMessage = "Device authorized. The daemon will finish binding without your password."
                deviceBindingIsError = false
                Haptics.success()
            } catch {
                deviceBindingMessage = "Couldn't authorize this device. Check the account session and try again."
                deviceBindingIsError = true
                Haptics.error()
            }
        }
    }
}

// MARK: - Shared palette (board sand-theme literals not in the semantic token set)

private enum OnboardingPalette {
    /// Peach kicker used over the terracotta hero (`heroKicker` #F6D8C5).
    static let heroKicker = Color(.sRGB, red: 0.965, green: 0.847, blue: 0.773, opacity: 1)
}

// MARK: - Lavender pixel brand-mark

private struct OnboardingBrandMark: View {
    var body: some View {
        RoundedRectangle(cornerRadius: 16, style: .continuous)
            .fill(
                AngularGradient(
                    colors: [
                        Color(.sRGB, red: 0.545, green: 0.435, blue: 0.690, opacity: 1), // #8b6fb0
                        Color(.sRGB, red: 0.690, green: 0.561, blue: 0.808, opacity: 1), // #b08fce
                        Color(.sRGB, red: 0.435, green: 0.353, blue: 0.588, opacity: 1), // #6f5a96
                        Color(.sRGB, red: 0.616, green: 0.498, blue: 0.753, opacity: 1), // #9d7fc0
                        Color(.sRGB, red: 0.545, green: 0.435, blue: 0.690, opacity: 1)
                    ],
                    center: .center,
                    angle: .degrees(45)
                )
            )
            .overlay(
                Canvas { ctx, size in
                    var x: CGFloat = 0
                    while x <= size.width { ctx.fill(Path(CGRect(x: x, y: 0, width: 1, height: size.height)), with: .color(.black.opacity(0.12))); x += 11 }
                    var y: CGFloat = 0
                    while y <= size.height { ctx.fill(Path(CGRect(x: 0, y: y, width: size.width, height: 1)), with: .color(.black.opacity(0.12))); y += 11 }
                }
            )
            .overlay(RoundedRectangle(cornerRadius: 16, style: .continuous).strokeBorder(.white.opacity(0.85), lineWidth: 2))
            .frame(width: 56, height: 56)
            .shadow(color: .black.opacity(0.4), radius: 12, x: 0, y: 8)
            .accessibilityHidden(true)
    }
}

// MARK: - Step 0 · value rows

private struct OnboardingValueRows: View {
    @Environment(\.lancerTokens) private var t

    var body: some View {
        VStack(alignment: .leading, spacing: 40) {
            row(title: "Approve actions from afar", detail: "Allow or deny risky steps in a tap") {
                Image(systemName: "checkmark").font(.system(size: 15, weight: .bold)).foregroundStyle(t.accent)
            }
            row(title: "Watch the terminal stream live", detail: "Every command, as it runs") {
                Text("›_").font(.dsMonoPt(15, weight: .semibold)).foregroundStyle(t.accent)
            }
            row(title: "Policy guardrails per host", detail: "Rules enforce on every machine") {
                Image(systemName: "shield.fill").font(.system(size: 15)).foregroundStyle(t.accent)
            }
        }
    }

    private func row<Icon: View>(title: String, detail: String, @ViewBuilder icon: () -> Icon) -> some View {
        HStack(spacing: 15) {
            RoundedRectangle(cornerRadius: 13, style: .continuous)
                .fill(t.surface2)
                .frame(width: 44, height: 44)
                .overlay(icon())
            VStack(alignment: .leading, spacing: 1) {
                Text(title).font(.dsSansPt(15, weight: .semibold)).foregroundStyle(t.text)
                Text(detail).font(.dsSansPt(12.5)).foregroundStyle(t.text4)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }
}

// MARK: - Step 1 · pairing

private struct OnboardingPairingBlock: View {
    @ObservedObject var client: E2ERelayClient
    @Binding var manualCode: String
    let pairingMessage: String?
    let onScan: () -> Void
    let onSubmitCode: (String) -> Void
    let canBindAccountDevice: Bool
    let deviceBindingMessage: String?
    let deviceBindingIsError: Bool
    let onBindAccountDevice: () -> Void

    @Environment(\.lancerTokens) private var t
    @FocusState private var codeFocused: Bool

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // On your desktop, run `lancerd pair` — it prints a QR + 6-digit code.
            Text("ON YOUR DESKTOP, RUN  lancerd pair")
                .font(.dsMonoPt(10, weight: .medium))
                .tracking(1.2)
                .foregroundStyle(t.text4)

            // Primary: scan the desktop's QR (camera; device only).
            Button(action: onScan) {
                HStack(spacing: 12) {
                    Image(systemName: "qrcode.viewfinder")
                        .font(.system(size: 22, weight: .semibold))
                        .foregroundStyle(t.accent)
                        .frame(width: 30)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Scan the QR on your desktop")
                            .font(.dsSansPt(15, weight: .semibold)).foregroundStyle(t.text)
                        Text("Point your camera at the code in your terminal")
                            .font(.dsSansPt(12)).foregroundStyle(t.text4)
                    }
                    Spacer(minLength: 0)
                    Image(systemName: "chevron.right").font(.system(size: 12, weight: .semibold)).foregroundStyle(t.text4)
                }
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(t.surface, in: RoundedRectangle(cornerRadius: 16, style: .continuous))
                .overlay(RoundedRectangle(cornerRadius: 16, style: .continuous).strokeBorder(t.accent.opacity(0.5), lineWidth: 1))
            }
            .buttonStyle(.plain)
            .accessibilityIdentifier("pairingScan")

            // Divider → manual entry.
            HStack(spacing: 10) {
                Rectangle().fill(t.border).frame(height: 1)
                Text("or enter the 6-digit code").font(.dsSansPt(12)).foregroundStyle(t.text4).fixedSize()
                Rectangle().fill(t.border).frame(height: 1)
            }

            TextField("000000", text: $manualCode)
                .keyboardType(.numberPad)
                .font(.dsDisplayPt(26, weight: .bold))
                .multilineTextAlignment(.center)
                .tracking(8)
                .focused($codeFocused)
                .onChange(of: manualCode) { _, v in
                    let digits = String(v.filter(\.isNumber).prefix(6))
                    if digits != v { manualCode = digits }
                    if digits.count == 6 { codeFocused = false; onSubmitCode(digits) }
                }
                .padding(.vertical, 16)
                .frame(maxWidth: .infinity)
                .background(t.surface, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                .overlay(RoundedRectangle(cornerRadius: 14, style: .continuous).strokeBorder(codeFocused ? t.accent : t.border, lineWidth: 1.5))
                .accessibilityIdentifier("pairingCodeField")

            Text(statusLabel)
                .font(.dsSansPt(12))
                .foregroundStyle(isPaired ? t.accent : t.text4)
                .frame(maxWidth: .infinity, alignment: .center)

            if let pairingMessage {
                Text(pairingMessage)
                    .font(.dsSansPt(12, weight: .medium))
                    .foregroundStyle(t.danger)
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
            }

            if canBindAccountDevice {
                Button(action: onBindAccountDevice) {
                    Label("bind this daemon to my account", systemImage: "qrcode.viewfinder")
                        .font(.dsSansPt(13, weight: .semibold))
                        .foregroundStyle(t.accent)
                        .frame(maxWidth: .infinity)
                        .padding(.top, 8)
                }
                .buttonStyle(.plain)
                .accessibilityIdentifier("accountDeviceBinding")
                Text("Scans a one-time daemon challenge. Lancer never asks for your account password on the host.")
                    .font(.dsSansPt(11.5))
                    .foregroundStyle(t.text4)
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
                if let deviceBindingMessage {
                    Text(deviceBindingMessage)
                        .font(.dsSansPt(12, weight: .medium))
                        .foregroundStyle(deviceBindingIsError ? t.danger : t.ok)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: .infinity)
                }
            }
        }
        .onChange(of: client.pairingState) { _, state in
            switch state {
            case .paired:        Haptics.success()
            case .pairingFailed: Haptics.error()
            case .unpaired, .waitingForPeer: break
            }
        }
    }

    private var isPaired: Bool { client.pairingState == .paired }

    private var statusLabel: String {
        switch client.pairingState {
        case .unpaired:        return client.connectionState == .disconnected ? "Enter or scan your desktop code to pair" : "Connecting…"
        case .waitingForPeer:  return "Waiting for your desktop…"
        case .paired:          return "Paired ✓"
        case .pairingFailed:   return "Pairing failed — re-scan or re-enter the code"
        }
    }
}

// MARK: - Step 2 · policy cards

private struct OnboardingPolicyCards: View {
    @Binding var selectedLevel: OnboardingCautionLevel

    @Environment(\.lancerTokens) private var t
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        VStack(spacing: 11) {
            ForEach(OnboardingCautionLevel.allCases) { level in
                let isSelected = selectedLevel == level
                Button {
                    Haptics.selection()
                    withAnimation(LancerMotion.resolved(.smooth(duration: 0.18, extraBounce: 0), reduceMotion: reduceMotion)) {
                        selectedLevel = level
                    }
                } label: {
                    HStack(spacing: 13) {
                        ZStack {
                            Circle()
                                .strokeBorder(isSelected ? t.accent : t.borderStrong, lineWidth: 2)
                                .frame(width: 24, height: 24)
                            Circle()
                                .fill(isSelected ? t.accent : .clear)
                                .frame(width: 9, height: 9)
                        }
                        VStack(alignment: .leading, spacing: 1) {
                            Text(level.title).font(.dsDisplayPt(16, weight: .bold)).foregroundStyle(t.text)
                            Text(level.detail).font(.dsSansPt(12.5)).foregroundStyle(t.text4)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        Spacer(minLength: 0)
                    }
                    .padding(15)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(
                        RoundedRectangle(cornerRadius: 16, style: .continuous).fill(t.surface)
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: 16, style: .continuous)
                            .strokeBorder(isSelected ? t.accent : t.border, lineWidth: 1.5)
                    )
                    .shadow(color: .black.opacity(isSelected ? 0.16 : 0.05), radius: isSelected ? 14 : 3, x: 0, y: isSelected ? 6 : 1)
                }
                .buttonStyle(.plain)
                .accessibilityIdentifier("policyPreset_\(level.rawValue)")
                .accessibilityValue(isSelected ? "selected" : "unselected")
            }
        }
    }
}

// MARK: - Gallery wrapper (DebugGalleryView route `onboarding-redesign`)

/// Visual-reference + XCUITest entry point. Renders the productized view with
/// no-op callbacks so the flow can be walked without leaving the gallery.
public struct OnboardingRedesignGalleryView: View {
    let startStep: Int
    @Environment(\.lancerTokens) private var t
    public init(startStep: Int = 0) { self.startStep = startStep }
    public var body: some View {
        OnboardingRedesignView(onContinue: {}, onSetupWorkspace: {}, startStep: startStep)
            .background(t.bg)
    }
}

// MARK: - Step model

private struct OnboardingRedesignStep: Identifiable {
    enum Kind { case value, pair, policy, sshSetup }

    let id: String
    let eyebrow: String
    let title: String
    let body: String
    let primaryAction: String
    let ctaArrow: Bool
    let kind: Kind

    static let all: [OnboardingRedesignStep] = [
        .init(
            id: "value",
            eyebrow: "your machines,",
            title: "in your pocket.",
            body: "Lancer is mission control for the coding agents running on your own machines. Here's what you get:",
            primaryAction: "Continue",
            ctaArrow: true,
            kind: .value
        ),
        .init(
            id: "pair",
            eyebrow: "step one",
            title: "Pair the bridge.",
            body: "End-to-end encrypted — your code never leaves your machines.",
            primaryAction: "Pair & continue",
            ctaArrow: false,
            kind: .pair
        ),
        .init(
            id: "policy",
            eyebrow: "almost there",
            title: "How much rope?",
            body: "Set how freely agents act. You can fine-tune this per host later.",
            primaryAction: "Continue",
            ctaArrow: true,
            kind: .policy
        ),
        .init(
            id: "sshSetup",
            eyebrow: "optional",
            title: "Enable SSH.",
            body: "Turn on a live terminal on your Mac. You can skip this — approvals and agent runs already work without it.",
            primaryAction: "Continue",
            ctaArrow: true,
            kind: .sshSetup
        ),
    ]
}

#Preview("Onboarding redesign gallery") {
    OnboardingRedesignGalleryView()
        .environment(\.lancerTokens, .light)
}
#endif
