import Testing
import Foundation
import CryptoKit
@testable import SecurityKit
@testable import LancerCore

// MARK: - OpenSSHKeyParser Tests
//
// Test vectors are real keys generated by OpenSSH (ssh-keygen) and embedded
// here as PEM strings. Key material in tests is disposable — these are
// NOT production keys. The passphrase for the encrypted vector is "testpassphrase".

@Suite("OpenSSHKeyParser")
struct OpenSSHKeyParserTests {

    // MARK: - Fixtures

    /// Unencrypted Ed25519 key (cipher: none, kdf: none).
    /// Generated: ssh-keygen -t ed25519 -N "" -C "test-key"
    private let plainEd25519PEM = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDgajRurDpEJxTuBg3Ya8pSVriTW41NEvkKwlvtBb2kiAAAAJDhzOZm4czm
    ZgAAAAtzc2gtZWQyNTUxOQAAACDgajRurDpEJxTuBg3Ya8pSVriTW41NEvkKwlvtBb2kiA
    AAAEDnbVWmNXytfzkhfu4B5u4weh0I8l7ZxtS547d1qrgLBuBqNG6sOkQnFO4GDdhrylJW
    uJNbjU0S+QrCW+0FvaSIAAAACHRlc3Qta2V5AQIDBAU=
    -----END OPENSSH PRIVATE KEY-----
    """

    /// Passphrase-protected Ed25519 key (cipher: aes256-ctr, kdf: bcrypt).
    /// Generated: ssh-keygen -t ed25519 -N "testpassphrase" -C "test-key-encrypted"
    private let encryptedEd25519PEM = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBN3BwNQg
    CLvcN7Qzj7YBdgAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIOY2SQ1Bu3IHRG3P
    maHMDQU+u5PlKLaYbX7soz2vH5vTAAAAoH1hAk9nlD6IO/9okoW90qRjOEPXBbXLoO5Fs9
    9cPzz8uVnyt3XeIFRR3fJ6Pd8RFcXcNPewzJBrdApSX2bjtvoyhgTHHpz3pM2T6yilvXQG
    ySI0IBApUpmYTpLSM7t0GWTW3myuh7m4pkjFZpiYSLpfpDEcP8OX+uiBStMjsOOZBcVaqa
    KCWOKLjZ3W6vEo6gs1kZriNWOpxuRJ21r1xLM=
    -----END OPENSSH PRIVATE KEY-----
    """

    /// RSA key in OpenSSH format — should be rejected with unsupportedKeyType.
    /// Generated: ssh-keygen -t rsa -b 2048 -N "" -C "test-rsa"
    private let rsaOpenSSHPEM = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAvuzErB1f8KOr6j6PJbtX3neenAlvW5kK5T8OOZJFDBvDcCGoHkE0
    SBR9qvugKq4SRcApgDqKGNfnN7xbmyAMB+Y6XEV6SolKpW/qAVFwrWJQc+g7EcrOfW3yso
    3Dfy/Ph/W6FoKpky7gMh35OgKObRZSuOlZkEh49ld+t+MIX6+7OuvhD/B4nz6C6FAf6nq5
    eOIkg7CENf05XhSLPlbCUR2EQzvhTyQ8zsJUwqQP13qnC4uIk5/hfvDcv3hHLlIH8M4Uw3
    vNIGZ4b591kAr3fgCEAXYIJIHOaLZvi8VJpyCk5LULxyKlJXaU7Pi8BbNHl+h30/qnWgVR
    V96e/jj2zQAAA8A5jdqvOY3arwAAAAdzc2gtcnNhAAABAQC+7MSsHV/wo6vqPo8lu1fed5
    6cCW9bmQrlPw45kkUMG8NwIageQTRIFH2q+6AqrhJFwCmAOooY1+c3vFubIAwH5jpcRXpK
    iUqlb+oBUXCtYlBz6DsRys59bfKyjcN/L8+H9boWgqmTLuAyHfk6Ao5tFlK46VmQSHj2V3
    634whfr7s66+EP8HifPoLoUB/qerl44iSDsIQ1/TleFIs+VsJRHYRDO+FPJDzOwlTCpA/X
    eqcLi4iTn+F+8Ny/eEcuUgfwzhTDe80gZnhvn3WQCvd+AIQBdggkgc5otm+LxUmnIKTktQ
    vHIqUldpTs+LwFs0eX6HfT+qdaBVFX3p7+OPbNAAAAAwEAAQAAAQA8A0BuuW0Gvuuy3acx
    PQoJq5/3fB+8swZxuLhH8GozvCZagLnPiL9eSNKXhDB8OesUcaqZ28y8smDDbDl/MTuW4A
    9IIa6m7zC/f8YWU/sPBPA0/rJSjWUKmBzJczYYLHcXTW4I1VloIjvmhPVp/pO2RmYKKY81
    gxJCnI4ATyS6rn57WBf/jw24OaayxM6ddWMIOb9Vfy7dVcWWxXURcate9P1XQYLTNKv8mL
    oOMq0uS2GBkOOUiuQPWQ7hMJg+j9f7PdqI/8W1itNhAY7dFGjwKYUB1nSxLiQWSWcgUIq5
    huM2ErQNurJ5AnyT4H6QPut/SzW55TT2/FklxEhRQ0YBAAAAgCaB6qb4PchzEDpWZAM5HX
    xWw9sKZp5UizCO8oDc5qTrz35KKQi5OzzppQejAkxGILX21K7CAbN2RPE95Zf5g6xpwPR+
    Is57qTPVT7KtOInqgSGKf0meCbTS9uGT63IeH1LJz5EWebfgsE2uBkTpaVgTjGStkX6SIV
    HqvEhMU3vWAAAAgQD1A8PUB7hzP1AtuzRRSWCrw3Nz83Z867CzGUn/f7o4jXFo/O+KfJXU
    nQEA+mr/KkGGD/TrBLZnOYpQ29Jppy1kn68xC3ApGWzrMOoZJZ1O19goyp7ok7XVEQIAbN
    D6YQ4RUHmvJZsKVtMtW+KdChmudECcxP/n+R1hPqXVnH7HsQAAAIEAx3wrfS3o6yMx2b6D
    SJYdudR9m5h/KzkkOVzP91PzxFA+fr0dyTGBl5nJZZdZodBo83zNIbdLZXcLs23xs/tcbe
    QvnonjGC4jfpU9XaAsKtRBvjE623gbJO6NZShnMtCKg7XC8Ntn/MloLoV9rwePtZhJ2AM2
    NqCdxVKeHerHg90AAAAIdGVzdC1yc2EBAgM=
    -----END OPENSSH PRIVATE KEY-----
    """

    // MARK: - Valid Ed25519 unencrypted

    @Test("Parse valid unencrypted Ed25519 OpenSSH key returns 32-byte seed")
    func parseValidPlainEd25519() throws {
        let seed = try OpenSSHKeyParser.parseEd25519(pem: plainEd25519PEM, passphrase: nil)
        #expect(seed.count == 32)
    }

    @Test("Parsed seed produces a valid KeyStore import")
    func parsedSeedIsValidForKeyStoreImport() async throws {
        let seed = try OpenSSHKeyParser.parseEd25519(pem: plainEd25519PEM, passphrase: nil)
        // KeyStore.importEd25519 will throw if the seed is not a valid Ed25519 scalar
        let store = KeyStore(service: "test.lancer.seed.\(UUID().uuidString)", inMemory: true)
        let info = try await store.importEd25519(tag: "seed-test", rawPrivate: seed, comment: "test")
        // Successful import means the seed was a valid 32-byte Ed25519 private key
        #expect(info.openSSH.hasPrefix("ssh-ed25519 "))
    }

    @Test("Parse is idempotent — same seed each call")
    func parseIsIdempotent() throws {
        let seed1 = try OpenSSHKeyParser.parseEd25519(pem: plainEd25519PEM, passphrase: nil)
        let seed2 = try OpenSSHKeyParser.parseEd25519(pem: plainEd25519PEM, passphrase: nil)
        #expect(seed1 == seed2)
    }

    @Test("Ignores extra whitespace and trailing newlines")
    func parseToleratesToleratesLeadingTrailingWhitespace() throws {
        let padded = "\n\n  " + plainEd25519PEM + "\n  \n"
        let seed = try OpenSSHKeyParser.parseEd25519(pem: padded, passphrase: nil)
        #expect(seed.count == 32)
    }

    // MARK: - Encrypted Ed25519 (aes256-ctr + bcrypt)

    @Test("Encrypted key without passphrase throws encryptedKeyRequiresPassphrase")
    func encryptedWithoutPassphraseThrows() throws {
        #expect(throws: OpenSSHKeyParser.ParseError.encryptedKeyRequiresPassphrase) {
            try OpenSSHKeyParser.parseEd25519(pem: encryptedEd25519PEM, passphrase: nil)
        }
    }

    @Test("Encrypted key with correct passphrase returns 32-byte seed")
    func encryptedWithCorrectPassphraseSucceeds() throws {
        let seed = try OpenSSHKeyParser.parseEd25519(pem: encryptedEd25519PEM, passphrase: "testpassphrase")
        #expect(seed.count == 32)
    }

    @Test("Encrypted key with wrong passphrase throws wrongPassphrase")
    func encryptedWithWrongPassphraseThrows() throws {
        #expect(throws: OpenSSHKeyParser.ParseError.wrongPassphrase) {
            try OpenSSHKeyParser.parseEd25519(pem: encryptedEd25519PEM, passphrase: "wrongpassword")
        }
    }

    @Test("Encrypted key with empty passphrase throws — not treated as unencrypted")
    func encryptedWithEmptyPassphraseThrows() throws {
        // Empty string is not nil — the parser will attempt decryption and fail the check
        do {
            let seed = try OpenSSHKeyParser.parseEd25519(pem: encryptedEd25519PEM, passphrase: "")
            // If we get here (extremely unlikely: random check words matched), the seed must still be 32 bytes
            // This branch should never execute for real data.
            #expect(seed.count == 32)
        } catch let err as OpenSSHKeyParser.ParseError {
            // Acceptable outcomes: wrongPassphrase or (if treated as nil) encryptedKeyRequiresPassphrase
            switch err {
            case .wrongPassphrase, .encryptedKeyRequiresPassphrase:
                break  // both are valid correct behaviors
            default:
                Issue.record("Unexpected error: \(err)")
            }
        } catch {
            Issue.record("Unexpected non-ParseError: \(error)")
        }
    }

    @Test("Encrypted seed differs from plain seed — not the same key")
    func encryptedSeedIsDistinctFromPlain() throws {
        let plainSeed = try OpenSSHKeyParser.parseEd25519(pem: plainEd25519PEM, passphrase: nil)
        let encryptedSeed = try OpenSSHKeyParser.parseEd25519(pem: encryptedEd25519PEM, passphrase: "testpassphrase")
        #expect(plainSeed != encryptedSeed, "The two test keys are different keypairs")
    }

    // MARK: - RSA key rejection

    @Test("RSA key in OpenSSH format throws unsupportedKeyType")
    func rsaKeyThrowsUnsupportedKeyType() throws {
        do {
            _ = try OpenSSHKeyParser.parseEd25519(pem: rsaOpenSSHPEM, passphrase: nil)
            Issue.record("Expected unsupportedKeyType to be thrown")
        } catch let err as OpenSSHKeyParser.ParseError {
            if case .unsupportedKeyType(let t) = err {
                #expect(t.contains("rsa"), "Error should mention the key type")
            } else {
                Issue.record("Expected unsupportedKeyType, got \(err)")
            }
        } catch {
            Issue.record("Unexpected non-ParseError: \(error)")
        }
    }

    @Test("RSA key error description is user-friendly and secret-free")
    func rsaKeyErrorDescriptionIsSafe() throws {
        do {
            _ = try OpenSSHKeyParser.parseEd25519(pem: rsaOpenSSHPEM, passphrase: nil)
        } catch let err as OpenSSHKeyParser.ParseError {
            let msg = err.errorDescription ?? ""
            #expect(!msg.isEmpty)
            // Must not contain raw base64 or binary data indicators
            #expect(!msg.contains("AAAA"))
            #expect(msg.contains("Ed25519") || msg.contains("ed25519") || msg.contains("supported"))
        } catch {
            Issue.record("Unexpected non-ParseError: \(error)")
        }
    }

    // MARK: - Malformed / invalid PEM

    @Test("Empty string throws invalidPEMFormat")
    func emptyStringThrows() {
        #expect(throws: OpenSSHKeyParser.ParseError.invalidPEMFormat) {
            try OpenSSHKeyParser.parseEd25519(pem: "", passphrase: nil)
        }
    }

    @Test("Missing BEGIN marker throws invalidPEMFormat")
    func missingBeginMarkerThrows() {
        let noBEGIN = plainEd25519PEM.replacingOccurrences(of: "-----BEGIN OPENSSH PRIVATE KEY-----", with: "")
        #expect(throws: OpenSSHKeyParser.ParseError.invalidPEMFormat) {
            try OpenSSHKeyParser.parseEd25519(pem: noBEGIN, passphrase: nil)
        }
    }

    @Test("Missing END marker throws invalidPEMFormat")
    func missingEndMarkerThrows() {
        let noEND = plainEd25519PEM.replacingOccurrences(of: "-----END OPENSSH PRIVATE KEY-----", with: "")
        #expect(throws: OpenSSHKeyParser.ParseError.invalidPEMFormat) {
            try OpenSSHKeyParser.parseEd25519(pem: noEND, passphrase: nil)
        }
    }

    @Test("Truncated base64 body throws truncatedData or invalidPEMFormat")
    func truncatedBodyThrows() {
        let lines = plainEd25519PEM.components(separatedBy: .newlines)
        // Take the markers + just the first data line → truncated
        let truncated = [lines[0], lines[1], lines.last!].joined(separator: "\n")
        do {
            _ = try OpenSSHKeyParser.parseEd25519(pem: truncated, passphrase: nil)
            Issue.record("Expected truncation error")
        } catch let err as OpenSSHKeyParser.ParseError {
            switch err {
            case .truncatedData, .invalidPEMFormat, .parsingFailed:
                break  // all acceptable for truncated input
            default:
                Issue.record("Unexpected error for truncated input: \(err)")
            }
        } catch {
            // Non-ParseError — acceptable; some truncated inputs fail at a lower level
        }
    }

    @Test("Random bytes between markers throw an appropriate error")
    func randomGarbageBetweenMarkersThrows() {
        let garbage = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        dGhpcyBpcyBub3QgYSByZWFsIGtleWZpbGVhYWFhYWFhYWFhYWFhYWFhYWE=
        -----END OPENSSH PRIVATE KEY-----
        """
        do {
            _ = try OpenSSHKeyParser.parseEd25519(pem: garbage, passphrase: nil)
            Issue.record("Expected parsing to fail for random bytes")
        } catch is OpenSSHKeyParser.ParseError {
            // Any ParseError is acceptable — we just require it throws
        } catch {
            // Non-ParseError also acceptable for random garbage input
        }
    }

    @Test("Non-PEM text throws invalidPEMFormat")
    func plainTextThrows() {
        #expect(throws: OpenSSHKeyParser.ParseError.invalidPEMFormat) {
            try OpenSSHKeyParser.parseEd25519(pem: "not a key at all", passphrase: nil)
        }
    }

    @Test("Bit-flipped ciphertext throws wrongPassphrase on decryption check")
    func bitFlippedEncryptedKeyThrows() throws {
        // Corrupt an early data line of the encrypted key. Corrupting the FIRST
        // data line targets the beginning of the OpenSSH blob (cipher/KDF header
        // and early ciphertext), which reliably breaks the check-word comparison
        // after decryption and triggers wrongPassphrase.
        //
        // Note: corrupting the LAST line can affect only padding/comment bytes
        // after the private key material, where the check words may still match —
        // so we target the first base64 data line instead.
        var lines = encryptedEd25519PEM.components(separatedBy: .newlines)
        var didFlip = false
        for i in 0..<lines.count {
            if !lines[i].hasPrefix("-----") && !lines[i].isEmpty && !didFlip {
                var chars = Array(lines[i])
                // Flip one character to something clearly different
                let mid = chars.count / 2
                chars[mid] = (chars[mid] == "A") ? "B" : "A"
                lines[i] = String(chars)
                didFlip = true
                break
            }
        }
        let corrupted = lines.joined(separator: "\n")
        do {
            _ = try OpenSSHKeyParser.parseEd25519(pem: corrupted, passphrase: "testpassphrase")
            Issue.record("Expected error from corrupted ciphertext")
        } catch is OpenSSHKeyParser.ParseError {
            // Any ParseError acceptable — corruption should always fail
        } catch {
            Issue.record("Unexpected non-ParseError: \(error)")
        }
    }

    // MARK: - Error descriptions (security: no key material in messages)

    @Test("invalidPEMFormat error description is non-empty and helpful")
    func invalidPEMErrorDescriptionIsHelpful() {
        let err = OpenSSHKeyParser.ParseError.invalidPEMFormat
        let msg = err.errorDescription ?? ""
        #expect(!msg.isEmpty)
        #expect(msg.contains("BEGIN") || msg.contains("key") || msg.contains("PEM"))
    }

    @Test("encryptedKeyRequiresPassphrase error description mentions passphrase")
    func encryptedErrorDescriptionMentionsPassphrase() {
        let err = OpenSSHKeyParser.ParseError.encryptedKeyRequiresPassphrase
        let msg = err.errorDescription ?? ""
        #expect(msg.localizedCaseInsensitiveContains("passphrase"))
    }

    @Test("wrongPassphrase error description does not echo any key bytes")
    func wrongPassphraseErrorDoesNotLeakData() {
        let err = OpenSSHKeyParser.ParseError.wrongPassphrase
        let msg = err.errorDescription ?? ""
        // Must not contain base64-like data (long runs of alphanum without spaces)
        let words = msg.split(separator: " ")
        for word in words {
            #expect(word.count < 50, "Error message word too long — possible key material leak: \(word)")
        }
    }

    // MARK: - KeyStore integration (in-memory)

    @Test("importEd25519FromPEM round-trips through KeyStore in-memory")
    func importFromPEMRoundTrip() async throws {
        let store = KeyStore(service: "test.lancer.parser.\(UUID().uuidString)", inMemory: true)
        let tag = UUID().uuidString
        let info = try await store.importEd25519FromPEM(tag: tag, pem: plainEd25519PEM, passphrase: nil, comment: "test")
        #expect(info.openSSH.hasPrefix("ssh-ed25519 "))
        #expect(info.sha256Fingerprint.hasPrefix("SHA256:"))

        // Reload and check
        let loaded = try await store.publicKey(tag: tag, comment: "test")
        #expect(loaded.sha256Fingerprint == info.sha256Fingerprint)
    }

    @Test("importEd25519FromPEM encrypted round-trips through KeyStore in-memory")
    func importEncryptedFromPEMRoundTrip() async throws {
        let store = KeyStore(service: "test.lancer.parser.enc.\(UUID().uuidString)", inMemory: true)
        let tag = UUID().uuidString
        let info = try await store.importEd25519FromPEM(
            tag: tag, pem: encryptedEd25519PEM, passphrase: "testpassphrase", comment: "enc-test"
        )
        #expect(info.openSSH.hasPrefix("ssh-ed25519 "))
        #expect(info.sha256Fingerprint.hasPrefix("SHA256:"))
    }

    @Test("importEd25519FromPEM with RSA key throws keyDecodeFailed")
    func importRSAKeyThrowsKeyDecodeFailed() async throws {
        let store = KeyStore(service: "test.lancer.parser.rsa.\(UUID().uuidString)", inMemory: true)
        let tag = UUID().uuidString
        do {
            _ = try await store.importEd25519FromPEM(tag: tag, pem: rsaOpenSSHPEM, passphrase: nil)
            Issue.record("Expected keyDecodeFailed to be thrown")
        } catch let err as LancerError {
            if case .keyDecodeFailed = err {
                // Expected
            } else {
                Issue.record("Expected keyDecodeFailed, got \(err)")
            }
        } catch {
            Issue.record("Unexpected non-LancerError: \(error)")
        }
    }
}
